name: build-push
run-name: 'build-push: source? ${{ github.event.inputs.source }} target? ${{ github.event.inputs.target }} - latest? ${{ github.event.inputs.latest }} - custom_tag? ${{ github.event.inputs.custom_tag }} - petsc? ${{ github.event.inputs.petsc_version }} - gcc? ${{ github.event.inputs.gcc_version }}'

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'github repository where source code is stored'
        required: true
        type: string
        default: "samuel-hg-engel/DAMASK"
      target:
        description: 'ghcr.io repository where image will be pushed to'
        required: true
        type: string
        default: "ghcr.io/samuel-hg-engel/damask:latest"
      latest:
        description: 'Push with "latest" tag?'
        required: true
        type: boolean
        default: true
      custom_tag:
        description: 'Specify a custom tag to push'
        required: false
        type: string
        default: ""
      petsc_version:
        description: 'PETSc version'
        required: true
        type: string
        default: '3.19.5'
      gcc_version:
        description: 'GCC version'
        required: true
        type: string
        default: '13.1.0'

jobs:
  build-push:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: damask:testing
          build-args: |
            damask_repo=${{ github.event.inputs.source }}
            PETSC_VERSION=${{ github.event.inputs.petsc_version }}
            GCC_V=${{ github.event.inputs.gcc_version }}
        
      - name: Test
        run: |
          expected="STOP 0"
          actual=$(docker run damask:testing --help 2>&1 >/dev/null)
          if [ "$expected" = "$actual" ]; then
            echo "Passed -   $actual"
          else
            echo "ERROR - Expected: $expected"
            echo "          Actual: $actual"
            status=1
          fi

          exit $status
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push custom_tag
        if: github.event.inputs.custom_tag != ''
        run: |
          docker image tag damask:testing ghcr.io/${{ github.event.inputs.target }}/damask:${{ github.event.inputs.custom_tag }}
          docker push ghcr.io/${{ github.event.inputs.target }}/damask:${{ github.event.inputs.custom_tag }}

      - name: Push latest
        if: github.event.inputs.latest == 'true'
        run: |
          docker image tag damask:testing ghcr.io/${{ github.event.inputs.target }}/damask:latest
          docker push ghcr.io/${{ github.event.inputs.target }}/damask:latest
